export const books = [
  {
    id: 1,
    title: "Crack the Coding Interview",
    author: "Gayle Laakmann McDowell",
    genre: "Technology",
    url: "https://m.media-amazon.com/images/I/61mIq2iJUXL._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 49.95,
    salePrice: 14.95,
    rating: 4.5,
    description:
      "The definitive guide to acing software engineering interviews. Covers 189 programming questions and solutions across data structures, algorithms, and system design — essential reading for anyone targeting top-tier tech companies.",
  },
  {
    id: 2,
    title: "Atomic Habits",
    author: "James Clear",
    genre: "Self-Help",
    url: "https://m.media-amazon.com/images/I/81ANaVZk5LL._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 39,
    salePrice: null,
    rating: 5,
    description:
      "A proven framework for building good habits and breaking bad ones. James Clear distills the latest research on habit formation into a practical guide that shows how tiny changes in behaviour produce remarkable results over time.",
  },
  {
    id: 3,
    title: "Can't Hurt Me",
    author: "David Goggins",
    genre: "Biography",
    url: "https://m.media-amazon.com/images/I/81gTRv2HXrL._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 29,
    salePrice: null,
    rating: 5,
    description:
      "David Goggins shares his astonishing life story and reveals that most of us only tap into 40% of our potential. Through radical self-discipline and mental toughness, he transformed himself from an overweight young man into a Navy SEAL and ultramarathon champion.",
  },
  {
    id: 4,
    title: "Deep Work",
    author: "Cal Newport",
    genre: "Productivity",
    url: "https://m.media-amazon.com/images/I/91nujEwIpYL._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 44,
    salePrice: 19,
    rating: 4.5,
    description:
      "Cal Newport argues that the ability to perform focused, distraction-free work is becoming increasingly rare and valuable. This book provides a rigorous training regimen for cultivating deep work as a core professional skill.",
  },
  {
    id: 5,
    title: "The 10X Rule",
    author: "Grant Cardone",
    genre: "Business",
    url: "https://m.media-amazon.com/images/I/71hjq42hvGL._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 32,
    salePrice: null,
    rating: 5,
    description:
      "Grant Cardone challenges you to set targets ten times higher than you think possible and take ten times the action you believe necessary. A blueprint for achieving extraordinary results in business and life by operating at a fundamentally different level of commitment.",
  },
  {
    id: 6,
    title: "Sell Or Be Sold",
    author: "Grant Cardone",
    genre: "Business",
    url: "https://m.media-amazon.com/images/I/616OvChM3RL._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 70,
    salePrice: 12.5,
    rating: 5,
    description:
      "Whether in business or life, Grant Cardone's central thesis is that you are always selling — either your ideas, your products, or yourself. This book delivers proven techniques for persuading others and closing any deal with confidence.",
  },
  {
    id: 7,
    title: "Rich Dad Poor Dad",
    author: "Robert T. Kiyosaki",
    genre: "Finance",
    url: "https://m.media-amazon.com/images/I/81bsw6fnUiL.jpg",
    originalPrice: 11,
    salePrice: 10,
    rating: 4,
    description:
      "The story of two fathers — one rich, one poor — and the lessons Robert Kiyosaki learned from each. A landmark personal finance book that challenges conventional thinking about money, work, and wealth-building through assets versus liabilities.",
  },
  {
    id: 8,
    title: "Cashflow Quadrant",
    author: "Robert T. Kiyosaki",
    genre: "Finance",
    url: "https://m.media-amazon.com/images/I/71+SWQ6xj1L._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 38,
    salePrice: 17.95,
    rating: 4.5,
    description:
      "The sequel to Rich Dad Poor Dad introduces the ESBI quadrant — Employee, Self-Employed, Business Owner, Investor. Kiyosaki explains why some people work less, earn more, and pay fewer taxes, and provides a roadmap for moving toward financial freedom.",
  },
  {
    id: 9,
    title: "48 Laws of Power",
    author: "Robert Greene",
    genre: "Strategy",
    url: "https://m.media-amazon.com/images/I/611X8GI7hpL._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 35,
    salePrice: 19.95,
    rating: 4.5,
    description:
      "Drawing on three thousand years of history, Robert Greene distills the essence of power into 48 laws derived from the philosophies of Machiavelli, Sun Tzu, and Clausewitz. An essential manual for anyone operating in competitive environments.",
  },
  {
    id: 10,
    title: "The 5 Second Rule",
    author: "Mel Robbins",
    genre: "Self-Help",
    url: "https://m.media-amazon.com/images/I/91wOERyhh7L._UF1000,1000_QL80_.jpg",
    originalPrice: 40,
    salePrice: null,
    rating: 5,
    description:
      "A deceptively simple technique for overcoming self-doubt, procrastination, and fear. Mel Robbins reveals how counting 5-4-3-2-1 activates the prefrontal cortex and interrupts the habit loops that keep you stuck, backed by neuroscience research.",
  },
  {
    id: 11,
    title: "How to Win Friends & Influence People",
    author: "Dale Carnegie",
    genre: "Self-Help",
    url: "https://m.media-amazon.com/images/I/71vK0WVQ4rL._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 30,
    salePrice: 20,
    rating: 5,
    description:
      "The timeless classic on human relations. Carnegie's principles for handling people, making friends, winning others to your way of thinking, and becoming a leader have influenced generations of business professionals and remain as relevant today as ever.",
  },
  {
    id: 12,
    title: "Mastery",
    author: "Robert Greene",
    genre: "Strategy",
    url: "https://m.media-amazon.com/images/I/51V3121nmkL._AC_UF1000,1000_QL80_.jpg",
    originalPrice: 30,
    salePrice: 12.95,
    rating: 4.5,
    description:
      "Robert Greene examines the lives of historical and contemporary masters — from Leonardo da Vinci to Paul Graham — to reveal the common path to greatness. A compelling argument that mastery is not a matter of genius but of sustained deliberate practice.",
  },
];
